// REGISTER
export const SPECIE_REGISTER_REQUEST = "SPECIE_REGISTER_REQUEST";
export const SPECIE_REGISTER_SUCESS = "SPECIE_REGISTER_SUCESS";
export const SPECIE_REGISTER_FAIL = "SPECIE_REGISTER_FAIL";
export const SPECIE_REGISTER_RESET = "SPECIE_REGISTER_RESET";

// LIST
export const SPECIE_LIST_REQUEST = "SPECIE_LIST_REQUEST";
export const SPECIE_LIST_SUCESS = "SPECIE_LIST_SUCESS";
export const SPECIE_LIST_FAIL = "SPECIE_LIST_FAIL";
export const SPECIE_LIST_RESET = "SPECIE_LIST_RESET";

// UPDATE
export const SPECIE_UPDATE_REQUEST = "SPECIE_UPDATE_REQUEST";
export const SPECIE_UPDATE_SUCESS = "SPECIE_UPDATE_SUCESS";
export const SPECIE_UPDATE_FAIL = "SPECIE_UPDATE_FAIL";
export const SPECIE_UPDATE_RESET = "SPECIE_UPDATE_RESET";

// DETAILS
export const SPECIE_DETAILS_REQUEST = "SPECIE_DETAILS_REQUEST";
export const SPECIE_DETAILS_SUCESS = "SPECIE_DETAILS_SUCESS";
export const SPECIE_DETAILS_FAIL = "SPECIE_DETAILS_FAIL";
export const SPECIE_DETAILS_RESET = "SPECIE_DETAILS_RESET";

// DELETE
export const SPECIE_DELETE_REQUEST = "SPECIE_DELETE_REQUEST";
export const SPECIE_DELETE_SUCESS = "SPECIE_DELETE_SUCESS";
export const SPECIE_DELETE_FAIL = "SPECIE_DELETE_FAIL";
export const SPECIE_DELETE_RESET = "SPECIE_DELETE_RESET";