# Generated by Django 3.2 on 2021-05-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('risk', models.CharField(blank=True, max_length=200, null=True)),
                ('habitat', models.CharField(blank=True, max_length=200, null=True)),
                ('kingdom', models.CharField(blank=True, max_length=200, null=True)),
                ('family', models.CharField(blank=True, max_length=200, null=True)),
                ('ecosistem', models.CharField(blank=True, max_length=200, null=True)),
                ('info_actual', models.TextField(blank=True)),
                ('movement', models.CharField(blank=True, max_length=200, null=True)),
                ('awareness', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=1000, verbose_name='Latitud')),
                ('altitude', models.DecimalField(decimal_places=16, max_digits=1000, verbose_name='Altitud')),
            ],
        ),
    ]
