# Generated by Django 3.2 on 2021-05-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='ong',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
